/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY REGENERATED by `npx convex dev`.
 * The stub here lets Next.js build before your first Convex deploy.
 *
 * @module
 */
import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export const api = anyApi;

/**
 * A utility for referencing Convex internal functions.
 */
export const internal = anyApi;
